/* PhantomForce — PhantomPlay Flagship Games.

   Substantially deeper PhantomPlay games (real progression,
   cross-network multiplayer via the existing workspace-relay room model,
   in-app tutorials) than any of the 23 existing built-in games. Following
   the exact precedent set by ./phantomplay-v2.ts: this file owns its own
   games array and a registerPhantomPlayFlagshipGames() merge-at-startup
   function, with an explicit "no V1/V2 source edits" goal — the existing
   PHANTOMPLAY_BUILT_IN_GAMES and PHANTOMPLAY_V2_GAMES arrays are never
   mutated in place, only pushed into (array push, like V2 already does to
   V1's array). Games ship in a later step; this file just wires the
   registration plumbing so app/games/<slug>/ folders can land independently
   of the catalog/server wiring.

   Each game, once added, is expected to live entirely under its own
   app/games/<slug>/ (or app/games/<slug>.html) path per the platform's
   file-format contract — this module only ever holds catalog metadata
   (PhantomPlayGame entries), never game logic. */

import { PHANTOMPLAY_BUILT_IN_GAMES, PHANTOMPLAY_ENGINE, type PhantomPlayGame } from "./phantomplay.js";

const UNREAL_ENGINE_LABEL = "Unreal Engine 5.8";
const unrealPlayerUrl = (gameId: string) => `/app/games/native/${gameId}?engine=unreal&version=5.8`;

// The flagship games are now native Unreal entries. launchUrl intentionally
// names the native player route so the catalog does not imply an obsolete web
// fallback for the Unreal-owned games.
export const PHANTOMPLAY_FLAGSHIP_GAMES: PhantomPlayGame[] = [
  {
    id: "cubetown",
    title: "CubeTown",
    summary: "Unreal Engine 5.8 native voxel adventure: mine, build, learn echoes, restore shrines, and fight the Rift Guardian.",
    description: "The Unreal-native Cubetown player is the current canonical build: a voxel island adventure inspired by Echoes of Wisdom and Minecraft, with mining, block placement, learned Echo companions, Wisdom Shrines, combat, waves, and a guardian finale. PhantomPlay still preserves web and other engine compatibility for unrelated uploads.",
    category: "Creative",
    tags: ["unreal", "native", "building", "voxel", "adventure", "echoes", "touch"],
    contentRating: "everyone",
    contentDescriptors: ["no_reading_required"],
    multiplayerDescriptor: "Together: cross-network relay rooms, host-authoritative shared building, guest placements stay local previews",
    chatDescriptor: "No player chat or voice — only fixed, pre-written resident dialogue",
    developer: "Tak",
    kind: "built_in",
    launchUrl: unrealPlayerUrl("cubetown"),
    thumbnail: "/app/assets/phantomplay/cubetown-cover.svg?v=1.0.0",
    featured: true,
    version: "5.8.0-unreal",
    controls: "Native Unreal player. WASD moves, mouse aims, E mines/interacts, Q places blocks, Shift dashes, Space uses Echo power, 1/2/3 choose block slots.",
    progressSupport: true,
    scoreSupport: true,
    engine: { tier: UNREAL_ENGINE_LABEL, minVersion: PHANTOMPLAY_ENGINE.version },
  },
  {
    id: "skyguard-arena",
    title: "Skyguard Arena",
    summary: "Bloons-style tower defense with free off-road Sentinel placement, one winding route, three-path upgrades, starter sentries, and Century Watch bosses.",
    description: "A lane-based tower-defense game rebuilt closer to classic Bloons-style play: one big winding route instead of split lanes, free off-road Sentinel placement, starter sentries, and a first round with one Driftling before air pressure begins. Spend Glint to place Sentinels, then customize each tower through Power, Reach, and Tech upgrade paths with crosspath limits. Century Watch escalates toward round 100, boss mechanics rotate every 10 rounds, and Room Duel support stays network-silent through PhantomPlay rooms.",
    category: "Strategy",
    tags: ["tower-defense", "strategy", "pvp", "waves", "touch"],
    contentRating: "everyone10",
    contentDescriptors: ["cartoon_action", "strategic_complexity", "competitive_play"],
    multiplayerDescriptor: "Room Duel: cross-network relay rooms, host-authoritative duel state with a documented spectator-side prediction/reconciliation model",
    chatDescriptor: "No player chat or voice",
    developer: "Tak",
    kind: "built_in",
    launchUrl: "/app/games/skyguard-arena/index.html?v=1.3.3",
    thumbnail: "/app/assets/phantomplay/skyguard-arena-cover.svg?v=1.0.0",
    featured: true,
    version: "1.3.3",
    controls: "Click/tap a Sentinel card, build anywhere off the road, then tune Power, Reach, and Tech upgrade paths. Q triggers Overcharge Pulse, P pauses, Escape deselects.",
    progressSupport: true,
    scoreSupport: true,
    engine: { tier: "arena-large-map", minVersion: PHANTOMPLAY_ENGINE.version },
  },
  {
    id: "crown-circuit",
    title: "Crown Circuit",
    summary: "Solo bot training plus 8-card/4-hand elixir lane duels with battle plans, Obsidian Relay, Oracle slows, Ram sieges, and room support.",
    description: "A royale-style lane battler: choose Balanced, Siege Push, Split Swarm, Control Lock, or Tempo Cycle before the match, then start Solo Training against Crown Bot to learn lane pressure, elixir timing, card cycling, and tower trades across multiple arenas including Obsidian Relay. Oracle cards apply real slows, Ram cards pressure towers, and Crown Bot cycles plan-biased decks.",
    category: "Strategy",
    tags: ["card", "lane", "royale", "solo", "bots", "training", "multiplayer", "pvp"],
    contentRating: "everyone10",
    contentDescriptors: ["strategic_complexity", "competitive_play"],
    multiplayerDescriptor: "Solo Training uses Crown Bot. Room mode is a two-player private PhantomPlay duel. No public matchmaking, chat, or voice.",
    chatDescriptor: "No player chat or voice",
    developer: "Tak",
    kind: "built_in",
    launchUrl: "/app/games/crown-circuit.html?v=1.3.3",
    thumbnail: "/app/assets/phantomplay/crown-circuit-cover.svg?v=1.0.0",
    featured: true,
    version: "1.3.3",
    controls: "Choose a battle plan, build an eight-card deck, drag from the four-card hand onto your side, and cycle back to the next card. Solo Training starts immediately against Crown Bot; Room mode waits for player two.",
    progressSupport: true,
    scoreSupport: true,
    engine: { tier: "arena-large-map", minVersion: PHANTOMPLAY_ENGINE.version },
  },
  {
    id: "cipher-keep",
    title: "Cipher Keep",
    summary: "A typing roguelike dungeon crawl through rooms, foes, clues, and vaults.",
    description: "Type words to move through a shifting procedural dungeon, defeat foes in real-time typing duels, crack sealed vaults, recover evidence for the Clue Journal, and shape the Echo Warden story through your deductions and final verdict.",
    category: "Focus",
    tags: ["typing", "roguelike", "dungeon", "keyboard", "procedural"],
    contentRating: "everyone",
    contentDescriptors: ["fantasy_conflict"],
    developer: "Tak",
    kind: "built_in",
    launchUrl: "/app/games/cipher-keep.html?v=2.1.1",
    thumbnail: "/app/assets/phantomplay/cipher-keep-cover.svg?v=1.0.0",
    featured: true,
    version: "2.1.1",
    controls: "Type to explore and fight. Backspace corrects mistakes. P or Escape pauses. Touch keyboard supported.",
    progressSupport: true,
    scoreSupport: true,
  },
  {
    id: "tidefront-tactics",
    title: "Tidefront Tactics",
    summary: "Wind-read artillery tactics with Skiff weapons, cratered seas, bots, and boss duels.",
    description: "A turn-based artillery/tactics duel on a deformable heightmap sea. Pick an angle, power, and one of three tools — reliable Brine Mortar, heavy cooldown Anchor Charge, or repositioning Tide Tether — then fire under gravity and shifting wind to crater the terrain and splash-damage any Skiff caught in the blast. Clear a 4-mission Campaign against the Leviathan Hulk boss, run 1v1 or 3-way Skirmish against difficulty-tunable bots, or join a Fleet Room where one device claims the Helm and pilots the shared battle while everyone else spectates the host's synced state live.",
    category: "Strategy",
    tags: ["artillery", "tactics", "turn-based", "pvp", "physics"],
    contentRating: "everyone10",
    contentDescriptors: ["strategic_complexity", "mild_destruction", "competitive_play"],
    multiplayerDescriptor: "Fleet Room: cross-network relay rooms, one Helm pilot with everyone else a read-only spectator mirroring host-pushed state",
    chatDescriptor: "No player chat or voice",
    developer: "Tak",
    kind: "built_in",
    launchUrl: "/app/games/tidefront-tactics.html?v=1.1.0",
    thumbnail: "/app/assets/phantomplay/tidefront-tactics-cover.svg?v=1.0.0",
    featured: true,
    version: "1.1.0",
    controls: "Arrow keys to adjust angle/power, Space to fire, 1/2/3 to switch tools, Escape to pause. Drag on the battlefield to aim, or use the on-screen touchpad on mobile.",
    progressSupport: true,
    scoreSupport: true,
  },
  {
    id: "kingdom-breakers",
    title: "Kingdom Breakers",
    summary: "Us-vs-them tower siege with longer Stonefall and Ember shots that actually reach.",
    description: "A physics-based siege/destruction game: drag to aim and fire one of three ammunition types — hard-hitting Stonefall Orbs, piercing Splinter Lances, or splash-damage Emberburst Charges — at a rigid-body-simulated fortress built from stone, timber, and ironclad blocks. Duel mode is your tower vs their tower; campaign mode pushes through six holds into the ironclad-cored Warlord's Anvil boss. Stars come from breach percentage, ammo conserved, and keeping every Warden un-harmed; knocking out a hold's glowing keystone block triggers a slow-motion final blow.",
    category: "Strategy",
    tags: ["siege", "destruction", "physics", "artillery", "campaign", "pvp", "touch"],
    contentRating: "everyone10",
    contentDescriptors: ["cartoon_action", "mild_destruction", "competitive_play"],
    multiplayerDescriptor: "Siege Party: cross-network relay rooms, host-probe race establishes host authority; everyone breaches their own copy of the fortress against a shared timer, but the shared live board currently only carries the host's own run (each player's result still saves individually to their own PhantomPlay history/leaderboard) — see known issues.",
    chatDescriptor: "No player chat or voice",
    developer: "Tak",
    kind: "built_in",
    launchUrl: "/app/games/kingdom-breakers.html?v=1.1.0",
    thumbnail: "/app/assets/phantomplay/kingdom-breakers-cover.svg?v=1.0.0",
    featured: true,
    version: "1.1.0",
    controls: "Press and drag anywhere on the field to aim — direction and distance from the siege engine set angle and power — then release to fire. Tap the ammo rack or press 1/2/3 to switch ammunition, Space/Enter fires while aiming, arrow keys nudge angle and power, and P (or the on-screen button) pauses. Touch and mouse/pointer input work the same way.",
    progressSupport: true,
    scoreSupport: true,
  },
  {
    id: "im-baked",
    title: "I'm Baked",
    summary: "Run a future cake shop through real order, oven, decoration, service, and shift-result loops.",
    description: "A complete cake-shop simulator with changing customer tickets, bake timing, layered procedural cakes, visual finishes, patience, grades, coins, streaks, Story Shift, and Rush Counter modes.",
    category: "Creative",
    tags: ["cooking", "cakes", "shop", "creative", "simulation", "touch"],
    contentRating: "everyone",
    contentDescriptors: ["simulated_economy"],
    developer: "Tak",
    kind: "built_in",
    launchUrl: "/app/games/im-baked.html?v=1.0.0",
    thumbnail: "/app/assets/phantomplay/im-baked-cover.svg?v=1.0.0",
    featured: true,
    version: "1.0.0",
    controls: "Choose the ticketed ingredients, stop the oven in the green, decorate, and serve.",
    progressSupport: true,
    scoreSupport: true,
    engine: { tier: "creative-sim", minVersion: PHANTOMPLAY_ENGINE.version },
  },
  {
    id: "phantom-empires",
    title: "Phantom Empires: Sovereign",
    summary: "A civilization-scale RTS with a living economy, four Ages, land and naval armies, siege warfare, weather, and a rival empire that fights back.",
    description: "Build a Citadel economy, command Villagers across Food, Wood, Gold, and Stone, raise Houses and military districts, advance through four Ages, train infantry, archers, cavalry, Starfall catapults, and War Galleys, control two river bridges, survive escalating Crimson war parties, and destroy the rival crown. The battlefield includes day/night and weather fronts, formations, control groups, minimap command, autosave, procedural battle audio, touch controls, Campaign, Skirmish, and Architect modes.",
    category: "Strategy",
    tags: ["rts", "civilization", "empire", "economy", "naval", "siege", "strategy", "touch"],
    contentRating: "everyone10",
    contentDescriptors: ["fantasy_conflict", "strategic_complexity", "competitive_play"],
    multiplayerDescriptor: "Single-player sovereign campaign and skirmish against an adaptive rival empire. No public matchmaking, chat, voice, or external networking.",
    chatDescriptor: "No player chat or voice",
    developer: "Tak",
    kind: "built_in",
    launchUrl: "/app/games/phantom-empires/index.html?v=1.0.0",
    thumbnail: "/app/assets/phantomplay/phantom-empires-cover.svg?v=1.0.0",
    featured: true,
    version: "1.0.0",
    controls: "Drag to select, right-click to command, WASD pans, wheel zooms, Space arms attack-move, H centers home, F selects army, Ctrl+1-6 assigns groups. Touch command bar included.",
    progressSupport: true,
    scoreSupport: true,
    engine: { tier: "PhantomPlay Strategy Engine 1.0", minVersion: PHANTOMPLAY_ENGINE.version },
  },
  {
    id: "phantom-ages",
    title: "Phantom Ages",
    summary: "Unreal Engine 5.8 native fixed-lane age battler with troop upgrades, siege counters, faster AI, and readable formations.",
    description: "The canonical Phantom Ages build is now the packaged Unreal-native lane war game. It stays simple and readable like Age of War, but the native player owns the modern battlefield, literal troop upgrade paths, multi-rank ranged firing, siege units, catapult tower pressure, springald anti-siege logic, tower shots, speed controls, economy pressure, and era progression.",
    category: "Strategy",
    tags: ["unreal", "native", "strategy", "age-of-war", "lane-battle", "siege", "upgrades"],
    contentRating: "everyone10",
    contentDescriptors: ["cartoon_action", "competitive_play", "strategic_complexity"],
    multiplayerDescriptor: "Single-player native strategy battle. No public matchmaking, chat, voice, or external networking.",
    chatDescriptor: "No player chat or voice",
    developer: "Tak",
    kind: "built_in",
    launchUrl: unrealPlayerUrl("phantom-ages"),
    thumbnail: "/app/assets/phantomplay/phantom-ages-cover.svg?v=1.0.0",
    featured: true,
    version: "5.8.0-unreal",
    controls: "Native Unreal player. 1-5 deploy units, Q/W/E/R/T/Y buy research, A advances age, Space triggers tower volley, F1/F2/F3 set game speed.",
    progressSupport: true,
    scoreSupport: true,
    engine: { tier: UNREAL_ENGINE_LABEL, minVersion: PHANTOMPLAY_ENGINE.version },
  },
  {
    id: "phantom-strike",
    title: "Phantom Strike",
    summary: "Unreal Engine 5.8 native tactical FPS with rifle handling, enemy squads, waves, extraction, HUD, and a neon command complex.",
    description: "The canonical Phantom Strike build is now the packaged Unreal-native player: modern tactical first-person movement, automatic rifle handling, aiming, recoil, reloads, headshots, hit markers, scoring, health and armor, enemy archetypes, escalating waves, extraction, and procedural near-future combat spaces.",
    category: "Arcade",
    tags: ["unreal", "native", "fps", "shooter", "first-person", "bots", "tactical"],
    contentRating: "teen",
    contentDescriptors: ["intense_action", "competitive_play"],
    multiplayerDescriptor: "Solo Ops uses labeled enemy squads. No public matchmaking, local multiplayer, chat, voice, or external networking.",
    chatDescriptor: "No player chat or voice",
    developer: "Tak",
    kind: "built_in",
    launchUrl: unrealPlayerUrl("phantom-strike"),
    thumbnail: "/app/assets/phantomplay/phantom-strike-cover.svg?v=1.0.0",
    featured: true,
    version: "5.8.0-unreal",
    controls: "Native Unreal player. Mouse looks, WASD moves, Shift sprints, Space jumps, left mouse fires, right mouse aims, R reloads.",
    progressSupport: true,
    scoreSupport: true,
    engine: { tier: UNREAL_ENGINE_LABEL, minVersion: PHANTOMPLAY_ENGINE.version },
  },
  {
    id: "phantom-legends",
    title: "Phantom Legends",
    summary: "Unreal Engine 5.8 native fantasy RTS and persistent base builder with workers, armies, towers, raids, resources, and saves.",
    description: "A distinct Unreal-native strategy game, separate from Phantom Ages: command workers, harvest Gold/Wood/Stone/Shards, build a stronghold, raise defenses, train guards, rangers, brutes, survive Rift raids, upgrade your base, break the Rift Gate, and keep campaign progress between sessions.",
    category: "Strategy",
    tags: ["unreal", "native", "rts", "base-builder", "fantasy", "economy", "armies"],
    contentRating: "everyone10",
    contentDescriptors: ["fantasy_conflict", "strategic_complexity", "competitive_play"],
    multiplayerDescriptor: "Single-player native RTS campaign foundation. No public matchmaking, chat, voice, or external networking.",
    chatDescriptor: "No player chat or voice",
    developer: "Tak",
    kind: "built_in",
    launchUrl: unrealPlayerUrl("phantom-legends"),
    thumbnail: "/app/assets/phantomplay/phantom-legends-cover.svg?v=1.0.0",
    featured: true,
    version: "5.8.0-unreal",
    controls: "Native Unreal player. WASD pans camera, left mouse selects squads, right mouse attacks, gathers, or moves, Tab selects army, 1 workers, 2 guards, 3 towers, 4 rangers, 5 brutes, U upgrades.",
    progressSupport: true,
    scoreSupport: true,
    engine: { tier: UNREAL_ENGINE_LABEL, minVersion: PHANTOMPLAY_ENGINE.version },
  },
];

let gamesRegistered = false;
export function registerPhantomPlayFlagshipGames() {
  if (gamesRegistered) return;
  gamesRegistered = true;
  for (const game of PHANTOMPLAY_FLAGSHIP_GAMES) {
    const existingIndex = PHANTOMPLAY_BUILT_IN_GAMES.findIndex((item) => item.id === game.id);
    if (existingIndex >= 0) {
      PHANTOMPLAY_BUILT_IN_GAMES[existingIndex] = game;
    } else {
      PHANTOMPLAY_BUILT_IN_GAMES.push(game);
    }
  }
}
