import assert from 'node:assert/strict';
import { mkdtemp } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createBusinessRecord, updateBusinessRecord, listBusinessRecords } from '../src/business-workspaces/business-records.js';
const root = await mkdtemp(join(tmpdir(), 'pf-studio-records-'));
const tenant = 'client-chicagoshots';
const gear = await createBusinessRecord(tenant, {kind:'gear',title:'Test camera',status:'available',metadata:{assetTag:'QA-CAMERA',location:'Test studio',checkoutTo:''}},'test',root);
const checked = await updateBusinessRecord(tenant,gear.id,{expectedVersion:1,status:'checked-out',metadata:{checkoutTo:'Test shoot',location:'Field'}},'test',root);
assert.equal(checked.metadata.assetTag,'QA-CAMERA');
assert.equal(checked.metadata.checkoutTo,'Test shoot');
assert.equal(checked.status,'checked-out');
await assert.rejects(()=>updateBusinessRecord('occasionally-odd',gear.id,{status:'available'},'test',root),/not found/);
await assert.rejects(()=>createBusinessRecord('occasionally-odd',{kind:'gear',title:'Wrong company'},'test',root),/workflow/);
await assert.rejects(()=>updateBusinessRecord(tenant,gear.id,{expectedVersion:1,status:'retired'},'test',root),/Refresh/);
const project = await createBusinessRecord(tenant,{kind:'project',title:'Test media day',status:'production',due:'2026-10-12',customer:'Test team'},'test',root);
assert.equal(project.customer,'Test team');
assert.equal((await listBusinessRecords(tenant,root)).length,2);
assert.equal((await listBusinessRecords('phantomforce',root)).length,0);
console.log('Studio records: 9 lifecycle, metadata, scope and stale-edit checks passed.');
