import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { mkdtemp, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { commerceSummary, executeCommerceCommand, getCommerceState } from "../src/business-workspaces/commerce-store.js";

const root = await mkdtemp(join(tmpdir(), "pf-commerce-domain-"));
const tenant = "occasionally-odd";
const second = "isolated-odd";
process.env.PHANTOMFORCE_BUSINESS_WORKSPACES = JSON.stringify([{ id: "occasionallyodd", tenantId: second, name: "Independent commerce", assistantContext: "Isolated test company" }]);
let checks = 0;
function check(condition: unknown, message: string) { assert.ok(condition, message); checks++; }
async function rejects(operation: () => Promise<unknown>, code: string) { await assert.rejects(operation, (error: any) => error.code === code); checks++; }
const command = (type: string, payload: unknown, scope = tenant, expectedRevision?: number) => executeCommerceCommand(scope, { type, payload, ...(expectedRevision === undefined ? {} : { expectedRevision }) }, "domain-test-owner", root);
const state = () => getCommerceState(tenant, root);
const order = (externalId: string, quantity: number, channel = "etsy", sku = "VASE") => ({ externalId, channel, customer: { name: "Example Buyer", externalCustomerId: "buyer-01" }, due: "2026-09-28T12:00:00.000Z", lines: [{ sku, quantity }] });

check((await state()).revision === 0, "Empty tenant is a real empty workspace");
await rejects(() => getCommerceState("client-chicagoshots", root), "COMMERCE_WORKSPACE_REQUIRED");
await rejects(() => getCommerceState("../occasionally-odd", root), "INVALID_BUSINESS_SCOPE");
await command("create-material", { name: "Black PLA", unit: "g", onHand: 1000, unitCost: 0.02 });
const material = (await state()).materials[0];
await command("create-product", { sku: "vase", name: "Original sculpted vase", price: 50, finishedStock: 2, printHours: 3,
  bom: [{ materialId: material.id, quantity: 100 }], laborCost: 5, overheadCost: 3, feePercent: 10, rightsStatus: "original" });
await command("create-printer", { name: "P2S", hoursPerDay: 8 });
let current = await state();
const product = current.products[0]; const printer = current.printers[0];
check(product.sku === "VASE", "SKUs normalize consistently");
check(commerceSummary(current).products[0].unitContribution === 35, "Contribution accounts for materials, fees, labor and overhead");
check(commerceSummary(current).products[0].profitPerPrinterHour === 11.67, "Contribution per printer-hour is rounded in currency");
await command("configure-channel", { channel: "etsy", enabled: true, accountLabel: "OO Etsy" });
await command("configure-channel", { channel: "tiktok-shop", enabled: true, accountLabel: "OO TikTok" });
current = await state();
check(current.outbox.filter((e) => e.type === "inventory" && e.sku === "VASE").reduce((sum, e) => sum + (e.available || 0), 0) === 2
  && current.outbox.filter((e) => e.type === "inventory").every((e) => e.globalAvailable === 2), "Conservative channel offer allocations sum to the shared pool rather than multiplying it");
const results = await Promise.all(Array.from({ length: 12 }, () => command("create-order", order("etsy-001", 5))));
current = await state();
check(current.orders.length === 1 && current.jobs.length === 1 && current.customers.length === 1, "Concurrent delivery retries create exactly one order, job and customer");
check(results.filter((r) => r.duplicate).length === 11, "All replayed identical channel orders report duplicates");
const first = current.orders[0]; const job = current.jobs[0];
check(job.stockQuantity === 2 && job.makeQuantity === 3 && job.printHours === 9, "Finished inventory reserves first; shortfall becomes print work");
check(current.materials[0].onHand === 1000 && commerceSummary(current).materials[0].reserved === 300, "Order intake reserves materials without consuming them");
check(commerceSummary(current).products[0].available === 0 && current.outbox.filter((e) => e.type === "inventory" && e.available === 0).length === 2, "All configured channels receive the same shared finished inventory snapshot");
check(current.outbox.every((e) => e.status === "blocked") && current.channels.every((c) => !c.adapterReady), "Queued external work never invents a provider connection or sync receipt");
const revision = current.revision;
await command("create-order", order("etsy-001", 5), tenant, 0);
check((await state()).revision === revision, "Idempotent order retry succeeds without a revision bump even with an old version");
await rejects(() => command("create-order", order("etsy-001", 6)), "ORDER_IDEMPOTENCY_CONFLICT");
await rejects(() => command("adjust-stock", { kind: "product", id: product.id, delta: -1, reason: "Bad stock count" }), "STOCK_RESERVED");
await rejects(() => command("create-product", { sku: "VASE", name: "Duplicate", price: 1 }), "SKU_EXISTS");
await rejects(() => command("create-product", { sku: "OTHER", name: "Cross-business BOM", price: 1, bom: [{ materialId: "foreign", quantity: 1 }] }), "COMMERCE_NOT_FOUND");
await rejects(() => command("create-printer", { name: "Invalid", hoursPerDay: 25 }), "COMMERCE_COMMAND_INVALID");
await rejects(() => command("create-order", { ...order("bad-date", 1), due: "2026-02-31" }), "COMMERCE_COMMAND_INVALID");
await rejects(() => command("create-material", { name: "Scope smuggling", unit: "each", onHand: 1, tenantId: second }), "COMMERCE_COMMAND_INVALID");
check((await state()).revision === revision, "Rejected commands leave the durable revision and inventory unchanged");
await rejects(() => command("create-order", order("missing", 1, "etsy", "DOES-NOT-EXIST")), "SKU_NOT_FOUND");
check((await state()).customers.length === 1, "Failed intake rolls back customer creation too");
await command("create-order", order("tiktok-001", 1, "tiktok-shop"));
await command("create-order", order("etsy-002", 1));
current = await state();
check(current.customers.length === 2, "Customer identity deduplicates within a channel and stays separate across providers");
check(current.jobs.slice(1).every((j) => j.stockQuantity === 0 && j.makeQuantity === 1), "Second channel cannot oversell finished goods reserved by the first");
await rejects(() => command("advance-job", { jobId: job.id, to: "ready" }), "JOB_TRANSITION_INVALID");
await rejects(() => command("ship-order", { orderId: first.id, carrier: "USPS", trackingNumber: "TEST001" }), "ORDER_NOT_READY");
await command("advance-job", { jobId: job.id, to: "printing", printerId: printer.id });
current = await state();
check(current.materials[0].onHand === 700 && current.jobs[0].materialsConsumed && current.printers[0].currentJobId === job.id, "Starting a print consumes exactly its BOM and claims the printer atomically");
await rejects(() => command("advance-job", { jobId: job.id, to: "printing", printerId: printer.id }), "JOB_TRANSITION_INVALID");
await rejects(() => command("advance-job", { jobId: current.jobs[1].id, to: "printing", printerId: printer.id }), "PRINTER_UNAVAILABLE");
await rejects(() => command("update-printer", { printerId: printer.id, status: "offline" }), "PRINTER_JOB_ACTIVE");
check((await state()).materials[0].onHand === 700, "Invalid repeated starts never consume materials twice");
await command("fail-job", { jobId: job.id, reason: "Layer separation; failed output discarded" });
current = await state();
check(current.materials[0].onHand === 700 && !current.jobs[0].materialsConsumed && current.printers[0].status === "idle", "Failed print preserves spent material and releases printer");
await command("advance-job", { jobId: job.id, to: "printing", printerId: printer.id });
check((await state()).materials[0].onHand === 400 && (await state()).jobs[0].attempts === 2, "Reprint consumes a new BOM exactly once");
await command("advance-job", { jobId: job.id, to: "quality-check" });
check((await state()).printers[0].currentJobId === null, "Completed printing frees capacity during QC");
await command("advance-job", { jobId: job.id, to: "packing" });
await command("advance-job", { jobId: job.id, to: "ready" });
check((await state()).orders[0].status === "ready", "Order readiness follows all of its jobs");
await command("ship-order", { orderId: first.id, carrier: "USPS", trackingNumber: "TEST001" });
current = await state();
check(current.products[0].finishedStock === 0 && current.orders[0].status === "shipped", "Shipping deducts only finished units; made output is already allocated to the order");
check(current.outbox.filter((e) => e.type === "fulfillment").length === 1 && current.outbox.find((e) => e.type === "fulfillment")?.status === "blocked", "Tracking is durably queued and truthfully blocked pending an adapter");
await rejects(() => command("ship-order", { orderId: first.id, carrier: "USPS", trackingNumber: "TEST001" }), "ORDER_NOT_READY");
check((await state()).products[0].finishedStock === 0, "Repeated shipping cannot deduct stock twice");

await command("create-order", order("cancel-unstarted", 2));
current = await state();
const cancelled = current.orders.find((o) => o.externalId === "cancel-unstarted")!;
const beforeReserved = commerceSummary(current).materials[0].reserved;
await command("cancel-order", { orderId: cancelled.id });
current = await state();
check(commerceSummary(current).materials[0].reserved === beforeReserved - 200 && current.materials[0].onHand === 400, "Cancellation releases unconsumed reservations without changing physical stock");
const restockOrder = current.orders.find((o) => o.externalId === "etsy-002")!;
const restockJob = current.jobs.find((j) => j.orderId === restockOrder.id)!;
await command("advance-job", { jobId: restockJob.id, to: "printing", printerId: printer.id });
await command("advance-job", { jobId: restockJob.id, to: "quality-check" });
await command("advance-job", { jobId: restockJob.id, to: "packing" });
await command("cancel-order", { orderId: restockOrder.id });
current = await state();
check(current.products[0].finishedStock === 1 && current.materials[0].onHand === 300, "Cancelling QC-passed output restocks only new finished goods, without refunding consumed materials");
await rejects(() => command("cancel-order", { orderId: restockOrder.id }), "ORDER_TRANSITION_INVALID");

await command("create-product", { sku: "STOCK", name: "Stock-only component", price: 5, finishedStock: 3, rightsStatus: "original" });
await command("create-order", order("stock-only", 2, "manual", "STOCK"));
current = await state();
const stockOrder = current.orders.find((o) => o.externalId === "stock-only")!;
const stockJob = current.jobs.find((j) => j.orderId === stockOrder.id)!;
check(stockJob.printHours === 0 && stockJob.makeQuantity === 0, "Stock-only order needs no printer hours");
for (const to of ["quality-check", "packing", "ready"]) await command("advance-job", { jobId: stockJob.id, to });
await command("ship-order", { orderId: stockOrder.id, carrier: "Local pickup", trackingNumber: "Pickup receipt 001" });
check((await state()).products.find((p) => p.sku === "STOCK")!.finishedStock === 1, "Stock-only items follow QC, packing and shipping without a printer");
await rejects(() => command("create-order", order("oversell-stock", 2, "manual", "STOCK")), "PRODUCTION_RECIPE_REQUIRED");

await command("create-product", { sku: "RIGHTS", name: "Pending artwork", price: 20, printHours: 2 });
await command("create-order", order("rights-test", 1, "manual", "RIGHTS"));
current = await state(); const rightsJob = current.jobs.find((j) => j.sku === "RIGHTS")!;
await rejects(() => command("advance-job", { jobId: rightsJob.id, to: "printing", printerId: printer.id }), "RIGHTS_AUTHORIZATION_REQUIRED");
await command("update-product", { productId: current.products.find((p) => p.sku === "RIGHTS")!.id, rightsStatus: "authorized", rightsReference: "License reference TEST-001" });
await command("advance-job", { jobId: rightsJob.id, to: "printing", printerId: printer.id });
await command("cancel-order", { orderId: rightsJob.orderId });
check((await state()).printers[0].status === "idle", "Cancelling a running print releases its printer");

await command("create-order", order("short-materials", 10));
current = await state(); const shortageJob = current.jobs.find((j) => j.orderId === current.orders.find((o) => o.externalId === "short-materials")!.id)!;
check(commerceSummary(current).warnings.some((w) => w.code === "MATERIAL_SHORTAGE"), "Material demand beyond stock surfaces a shortage");
const beforeShortage = current.revision;
await rejects(() => command("advance-job", { jobId: shortageJob.id, to: "printing", printerId: printer.id }), "MATERIAL_SHORTAGE");
check((await state()).revision === beforeShortage && (await state()).printers[0].status === "idle", "Blocked print fails atomically without occupying its printer");
await command("update-printer", { printerId: printer.id, status: "offline" });
let summary = commerceSummary(await state(), new Date("2026-09-28T08:00:00Z"));
check(summary.warnings.some((w) => w.code === "NO_PRINTER_CAPACITY") && summary.warnings.some((w) => w.code === "SLA_AT_RISK"), "Offline printers expose both capacity and deadline warnings");
check(summary.products.every((p) => p.makeToOrderCapacity === 0), "Unavailable machines remove made-to-order capacity");
await command("update-printer", { printerId: printer.id, status: "idle", hoursPerDay: 1 });
summary = commerceSummary(await state(), new Date("2026-09-29T08:00:00Z"));
check(summary.warnings.some((w) => w.code === "CAPACITY_OVERBOOKED") && summary.warnings.some((w) => w.code === "ORDER_OVERDUE"), "Overbooking and overdue work are explicit");

const secondState = await getCommerceState(second, root);
check(secondState.products.length === 0 && secondState.orders.length === 0, "Mapped businesses get separate durable namespaces");
await command("create-product", { sku: "VASE", name: "Independent item", price: 99 }, second);
await rejects(() => command("adjust-stock", { kind: "product", id: product.id, delta: 1, reason: "Foreign object" }, second), "COMMERCE_NOT_FOUND");
check((await getCommerceState(second, root)).products[0].price === 99 && (await state()).products[0].price === 50, "Same SKU in another business cannot read or alter the first business");
const oldRevision = (await state()).revision;
const parallel = await Promise.allSettled([command("adjust-stock", { kind: "material", id: material.id, delta: 10, reason: "Count A" }, tenant, oldRevision), command("adjust-stock", { kind: "material", id: material.id, delta: 20, reason: "Count B" }, tenant, oldRevision)]);
check(parallel.filter((r) => r.status === "fulfilled").length === 1 && parallel.filter((r) => r.status === "rejected").length === 1, "Optimistic revision checks prevent concurrent stale writes");
const beforeConcurrent = (await state()).materials[0].onHand;
await Promise.all(Array.from({ length: 10 }, () => command("adjust-stock", { kind: "material", id: material.id, delta: 1, reason: "Serialized receipt" })));
check((await state()).materials[0].onHand === beforeConcurrent + 10, "Single-writer serialization loses no concurrent stock adjustment");
await command("configure-channel", { channel: "etsy", enabled: false });
check((await state()).outbox.filter((e) => e.channel === "etsy" && e.type === "inventory").every((e) => e.available === 0), "Disabling a channel replaces stale offers with blocked zero-quantity withdrawal intents");

const customerOrder = (externalId: string, customer: { name: string; email?: string; externalCustomerId?: string }, channel = "manual", scope = tenant) =>
  command("create-order", { ...order(externalId, 1, channel), customer }, scope);
await customerOrder("email-first", { name: "Same Name", email: "  Buyer@Example.com  " });
await customerOrder("email-second", { name: "Updated Display Name", email: "buyer@example.COM" });
current = await state();
const emailFirst = current.orders.find((o) => o.externalId === "email-first")!;
const emailSecond = current.orders.find((o) => o.externalId === "email-second")!;
check(emailFirst.customerId === emailSecond.customerId, "ID-less customers reuse normalized email within the same channel");
check(current.customers.find((c) => c.id === emailFirst.customerId)!.email === "Buyer@Example.com", "Email comparison preserves the first customer's display spelling");
check(emailFirst.customer.name === "Same Name" && emailFirst.customer.email === "Buyer@Example.com"
  && emailSecond.customer.name === "Updated Display Name" && emailSecond.customer.email === "buyer@example.COM", "New customer details never overwrite earlier order snapshots");
await customerOrder("email-other-channel", { name: "Same Name", email: "buyer@example.com" }, "etsy");
await customerOrder("email-other-address", { name: "Same Name", email: "different@example.com" });
await customerOrder("email-provider-one", { name: "Same Name", email: "buyer@example.com", externalCustomerId: "explicit-id-1" });
await customerOrder("email-provider-two", { name: "Same Name", email: "buyer@example.com", externalCustomerId: "explicit-id-2" });
await customerOrder("email-provider-replay", { name: "Changed Name", email: "changed@example.com", externalCustomerId: "explicit-id-1" });
await customerOrder("email-unidentified", { name: "Changed Name", email: "changed@example.com" });
await customerOrder("email-provider-only", { name: "Provider Buyer", email: "provider-only@example.com", externalCustomerId: "explicit-id-only" });
await customerOrder("email-idless-only", { name: "Provider Buyer", email: "provider-only@example.com" });
await customerOrder("name-only-first", { name: "Same Name" });
await customerOrder("name-only-second", { name: "Same Name" });
current = await state();
const customerIdFor = (externalId: string) => current.orders.find((o) => o.externalId === externalId)!.customerId;
check(customerIdFor("email-other-channel") !== emailFirst.customerId, "Email fallback never merges customers across source channels");
check(customerIdFor("email-other-address") !== emailFirst.customerId, "Matching names with different emails remain different customers");
check(new Set([emailFirst.customerId, customerIdFor("email-provider-one"), customerIdFor("email-provider-two")]).size === 3, "Distinct explicit provider IDs stay separate even when email and name match");
check(customerIdFor("email-provider-one") === customerIdFor("email-provider-replay"), "Explicit provider identity remains authoritative when email and name change");
check(customerIdFor("email-unidentified") !== customerIdFor("email-provider-one"), "An ID-less email does not merge into a provider-identified customer");
check(customerIdFor("email-provider-only") !== customerIdFor("email-idless-only"), "Even an identical stored email cannot override a provider customer's explicit identity");
check(customerIdFor("name-only-first") !== customerIdFor("name-only-second"), "Names alone never deduplicate customers");
await command("adjust-stock", { kind: "product", id: (await getCommerceState(second, root)).products[0].id, delta: 1, reason: "Isolated identity fixture" }, second);
await customerOrder("email-first", { name: "Same Name", email: "buyer@example.com" }, "manual", second);
check((await getCommerceState(second, root)).orders[0].customerId !== emailFirst.customerId, "Identical manual customer email in another organization remains separate");
const path = join(root, createHash("sha256").update(second).digest("hex") + ".json");
const raw = JSON.parse(await readFile(path, "utf8")); raw.products[0].tenantId = tenant;
await writeFile(path, JSON.stringify(raw));
await rejects(() => getCommerceState(second, root), "COMMERCE_SCOPE_INVALID");
await writeFile(path, "{broken");
await rejects(() => command("create-material", { name: "Must not reset", unit: "each" }, second), "COMMERCE_STORE_INVALID");
check(await readFile(path, "utf8") === "{broken", "Corrupt data is not silently reset or overwritten");
console.log(`PASS business commerce: ${checks} behavioral checks; durable isolation, inventory, order idempotency, concurrency, production/reprints, QC, shipping, cancellations, economics, SLA and truthful outbox.`);
