ALTER TABLE "Contact"
  ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'new',
  ADD COLUMN IF NOT EXISTS "type" TEXT NOT NULL DEFAULT 'prospect',
  ADD COLUMN IF NOT EXISTS "value" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "nextStep" TEXT,
  ADD COLUMN IF NOT EXISTS "notes" TEXT,
  ADD COLUMN IF NOT EXISTS "source" TEXT,
  ADD COLUMN IF NOT EXISTS "website" TEXT,
  ADD COLUMN IF NOT EXISTS "avatarUrl" TEXT,
  ADD COLUMN IF NOT EXISTS "socials" JSONB,
  ADD COLUMN IF NOT EXISTS "tags" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN IF NOT EXISTS "fitScore" INTEGER,
  ADD COLUMN IF NOT EXISTS "qualification" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN IF NOT EXISTS "outreach" TEXT,
  ADD COLUMN IF NOT EXISTS "crmStage" TEXT,
  ADD COLUMN IF NOT EXISTS "dueAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "lastTouchAt" TIMESTAMP(3);

CREATE INDEX IF NOT EXISTS "Contact_orgId_status_idx" ON "Contact"("orgId", "status");
CREATE INDEX IF NOT EXISTS "Contact_orgId_updatedAt_idx" ON "Contact"("orgId", "updatedAt");

CREATE TABLE IF NOT EXISTS "CrmSettings" (
  "orgId" TEXT NOT NULL,
  "dailyPullTarget" INTEGER NOT NULL DEFAULT 5,
  "sourceMode" TEXT NOT NULL DEFAULT 'manual',
  "notes" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,

  CONSTRAINT "CrmSettings_pkey" PRIMARY KEY ("orgId"),
  CONSTRAINT "CrmSettings_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "Org"("id") ON DELETE CASCADE ON UPDATE CASCADE
);
